### ISSUE TITLE
Double click crash

### ISSUE THREAD

**Issue by STPLAmrut** [Park-SM/ParkDateTimePicker#11]
If I click twice on date, it gets crash

**Comment by Park-SM** [comment]
@STPLAmrut 
Thank you for the reporting.
I will fix it to version 1.0.1 and distribute it.

**Comment by Park-SM** [comment]
Resolved it in [1.0.1](https://github.com/Park-SM/ParkDateTimePicker/releases/tag/1.0.1) version.
